[project]
name = "hello-world-clj"
version = "0.1.0"
description = "A simple Clojure hello-world example using Boilermaker"
default_lang = "clojure"
repository = "https://github.com/yeajustmars/hello-world-clj"
authors = ["yeajustmars <yeajustmars@gmail.com>"]
keywords = ["boilermaker", "example", "clojure"]
website = "https://dev/templates/hello-world-clj"
license = "MIT"

[variables]
recipient = "Boilermaker"
repl_port = 40000
